import { CASCClient, WDCReader, DBDParser } from '@rhyster/wow-casc-dbc';
import { writeFileSync } from 'node:fs';
const region='us', product=process.env.PRODUCT||'wowt';
const outPath=process.argv[2];
const version = await CASCClient.getProductVersion(region, product);
const client = new CASCClient(region, product, version);
await client.init(); await client.loadRemoteTACTKeys();
async function db2(fdid){
  const ks=client.getContentKeysByFileDataID(fdid); if(!ks?.length) throw new Error('no ckey '+fdid);
  const k=ks.find(d=>!!(d.localeFlags & CASCClient.LocaleFlags.enUS))||ks[0];
  const r=await client.getFileByContentKey(k.cKey,true);
  return DBDParser.parse(new WDCReader(r.buffer,r.blocks));
}
const jes=await db2(1134413);
const encSpells=new Set();
for(const id of jes.getAllIDs()){ const s=Number(jes.getRowData(id)?.SpellID); if(s>0) encSpells.add(s); }

// SpellEffect.Effect values that create an aura on the target.
const AURA=new Set([6,27,35,65,119,128,129,143,224]);
// SpellEffect.ImplicitTarget is a 2-element array [TargetA, TargetB] of WoW
// implicit-target enum values. We want auras the encounter applies TO PLAYERS
// (players are "enemies" from the boss's point of view), and NOT the boss's own
// self-buffs (Enrage) or buffs it grants allied adds (Bloodlust, heals). An aura
// effect counts as player-facing when at least one of its targets is hostile /
// any / unknown; it is "selfish" only when EVERY target is caster-self or friendly.
// (Long-stable Blizzard values; unknown values fail OPEN so a new target enum
// never silently hides real debuffs. Verified: Imperator's Glory 1270853 auras
// target [1]=caster -> selfish -> dropped; Rejuvenation 774 targets [21]=ally.)
const CASTER=new Set([1,18,22,32]);                             // aura on the boss itself
const FRIENDLY=new Set([3,4,20,21,29,30,31,33,34,35,37,56,57]); // aura on allies/party/raid
const SELFISH=new Set([...CASTER,...FRIENDLY]);
const TRIGGER_DEPTH=3; // journal spell -> trigger -> trigger -> trigger

const se=await db2(1140088);
// One pass, compact maps (holding full rows OOMs -- SpellEffect is ~1M rows):
//   auraPF[sp]  = spell sp has an APPLY_AURA effect with a player-facing target
//                 (hostile/any/unknown, or no target data -> fail open).
//   auraAny[sp] = spell sp has ANY APPLY_AURA effect (target irrelevant).
//   triggers[sp] = Set of spellIDs sp triggers (EffectTriggerSpell on ANY effect).
// Following the trigger chain recovers cast->trigger->debuff abilities like Void
// Marked (1280015 has a script effect that triggers 1280023, the actual aura).
// NOTE: the emitted sets are keyed by the JOURNAL ROOT spellID, not the applied
// aura's — correct for their only consumer (gating Journal ability rows in
// core/encounter_catalog.lua, which looks up by section spellID = the root).
// Do NOT feed these IDs into exact-ID aura filters: for trigger-applied
// abilities the aura that actually lands carries the TRIGGERED spellID.
const auraPF=new Map();
const auraAny=new Map();
const triggers=new Map();
for(const id of se.getAllIDs()){ const r=se.getRowData(id); if(!r) continue;
  const sp=Number(r.SpellID); if(!(sp>0)) continue;
  const trig=Number(r.EffectTriggerSpell);
  if(trig>0){ let s=triggers.get(sp); if(!s){ s=new Set(); triggers.set(sp,s); } s.add(trig); }
  if(!AURA.has(Number(r.Effect))) continue;
  auraAny.set(sp,true);
  const it=r.ImplicitTarget; const arr=Array.isArray(it)?it:[it];
  let pf=false, hadTarget=false;
  for(const x of arr){ const n=Number(x); if(!n) continue; hadTarget=true; if(!SELFISH.has(n)){ pf=true; break; } }
  if(!hadTarget) pf=true; // aura with no target data -> fail open (player-facing)
  if(pf) auraPF.set(sp,true);
}
// Walk the trigger chain from `root`; report whether it reaches a player-facing
// aura and whether it reaches ANY aura at all.
function classify(root){
  const seen=new Set([root]); let frontier=[root]; let anyAura=false;
  for(let d=0; d<=TRIGGER_DEPTH && frontier.length; d++){
    const next=[];
    for(const sp of frontier){
      if(auraPF.get(sp)) return { pf:true, anyAura:true };
      if(auraAny.get(sp)) anyAura=true;
      const ts=triggers.get(sp); if(ts) for(const t of ts){ if(!seen.has(t)){ seen.add(t); next.push(t); } }
    }
    frontier=next;
  }
  return { pf:false, anyAura };
}

const result=[], buffs=[];
for(const s of encSpells){ const cl=classify(s);
  if(cl.pf) result.push(s);            // player-facing debuff
  else if(cl.anyAura) buffs.push(s);   // aura, but only ever on self/allies -> boss/ally buff
}
result.sort((a,b)=>a-b); buffs.sort((a,b)=>a-b);
// emit Lua set, 10 per line
let lua=`-- GENERATED by tools/encounter_aura_gen/gen_encounter_aura_data.mjs -- DO NOT EDIT BY HAND.
-- Encounter Journal ability spellIDs that apply an aura TO PLAYERS (a debuff the
-- boss/encounter puts on you), for the Auras > Encounters browser aura filter.
-- An ability counts if IT or anything in its spell-trigger chain applies an aura
-- with a hostile target; boss self-buffs (Enrage, Imperator's Glory) and ally
-- buffs/heals (Bloodlust) are excluded. Source: WoW client DB2 tables (Journal-
-- EncounterSection x SpellEffect APPLY_AURA + ImplicitTarget + EffectTriggerSpell)
-- for build ${version.VersionsName}.
-- Regenerate per patch: PRODUCT=wowt node tools/encounter_aura_gen/gen_encounter_aura_data.mjs <path>
local _, ns = ...
-- [spellID] = true  (ability applies a PLAYER-FACING aura -> show in the browser).
-- Absent-and-not-in-the-buff-set spellIDs fall back to the Adventure-Guide icon-
-- flag heuristic in core/encounter_catalog.lua.
ns.QUI_EncounterAuraSpells = {
`;
for(let i=0;i<result.length;i+=10){
  lua+='\t'+result.slice(i,i+10).map(s=>`[${s}]=true`).join(', ')+',\n';
}
lua+=`}
-- [spellID] = true  (ability applies an aura ONLY to the boss itself or its allies
-- -- a self-buff/ally-buff, NOT a player debuff). This set VETOES the icon-flag
-- heuristic so a boss buff that Blizzard happens to flag (e.g. Imperator's Glory)
-- never shows in the player-debuff browser. See core/encounter_catalog.lua.
ns.QUI_EncounterBuffSpells = {
`;
for(let i=0;i<buffs.length;i+=10){
  lua+='\t'+buffs.slice(i,i+10).map(s=>`[${s}]=true`).join(', ')+',\n';
}
lua+='}\n';
writeFileSync(outPath, lua);
console.error(`build ${version.VersionsName}: ${encSpells.size} encounter spells -> ${result.length} player-facing, ${buffs.length} boss/ally buffs -> ${outPath} (${(lua.length/1024).toFixed(0)}KB)`);
console.error('Void Marked(1280015) in aura set:', result.includes(1280015), '(needs trigger-follow)');
console.error("Imperator's Glory(1270853) in buff set:", buffs.includes(1270853), '(1270853 has no JES section in this build -- veto only bites if the section spellID applies a caster-target aura)');
console.error('Smashed(1241844) in aura set:', result.includes(1241844));
